# Generated by Django 4.2.9 on 2024-01-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0003_customer_email_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
