# Generated by Django 4.2.3 on 2024-01-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0006_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Enter the address here', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
