# Generated by Django 4.2.3 on 2024-01-31 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0009_remove_item_brand_remove_item_model_brand_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcmsApp.brand'),
        ),
    ]
