# Generated by Django 4.2.3 on 2024-01-31 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0011_complaints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaints',
            new_name='Complaint',
        ),
    ]
