# Generated by Django 4.2.3 on 2024-01-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0012_rename_complaints_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='customer',
        ),
        migrations.AddField(
            model_name='complaint',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
