# Generated by Django 4.2.3 on 2024-01-31 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0013_remove_complaint_customer_complaint_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='customer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rcmsApp.customer'),
        ),
    ]
