# Generated by Django 4.2.3 on 2024-01-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0014_remove_complaint_customer_name_complaint_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='phone_number',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
