# Generated by Django 4.2.3 on 2024-01-31 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0015_complaint_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='complaint',
            name='brand',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rcmsApp.brand'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint',
            field=models.TextField(blank=True, default='', help_text='Enter the issue faced', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='item',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rcmsApp.item'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='model',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rcmsApp.model'),
        ),
    ]
