# Generated by Django 4.2.3 on 2024-01-31 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0018_complaintstatus_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.DeleteModel(
            name='ComplaintStatus',
        ),
    ]
