# Generated by Django 4.2.3 on 2024-01-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0019_remove_complaint_status_delete_complaintstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Temporarily Closed', 'Temporarily Closed')], default='Open', max_length=20),
        ),
    ]
