# Generated by Django 4.2.3 on 2024-01-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0020_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='test',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Temporarily Closed', 'Temporarily Closed')], default='Open', max_length=20),
        ),
    ]
