# Generated by Django 4.2.3 on 2024-01-31 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0022_remove_complaint_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineers',
            name='customer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rcmsApp.customer'),
        ),
    ]
