# Generated by Django 4.2.3 on 2024-01-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0023_engineers_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.CharField(blank=True, default='', help_text='Enter the issue faced', max_length=20, null=True),
        ),
    ]
