# Generated by Django 4.2.3 on 2024-01-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0024_alter_complaint_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='actual_complaint',
            field=models.CharField(blank=True, default='', help_text='Real issue', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_raised_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='solution_found',
            field=models.CharField(blank=True, default='', help_text='Real issue', max_length=200, null=True),
        ),
    ]
