# Generated by Django 4.2.3 on 2024-01-31 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0025_complaint_actual_complaint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_raised_on',
        ),
        migrations.AddField(
            model_name='complaint',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
