# Generated by Django 4.2.3 on 2024-01-31 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0027_remove_engineers_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engineers',
            new_name='Engineer',
        ),
    ]
