# Generated by Django 4.2.3 on 2024-01-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0028_rename_engineers_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='bill_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
