# Generated by Django 4.2.3 on 2024-01-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0030_alter_complaint_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='bill_amount',
            field=models.CharField(blank=True, default=0, max_length=5, null=True),
        ),
    ]
