# Generated by Django 4.2.3 on 2024-02-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0032_alter_complaint_solution_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
