# Generated by Django 4.2.3 on 2024-02-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0033_complaint_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='customer_phone_number',
        ),
    ]
