# Generated by Django 4.2.3 on 2024-02-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0034_remove_complaint_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=50)),
                ('productcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcmsApp.productcategory')),
            ],
        ),
    ]
