# Generated by Django 4.2.3 on 2024-02-07 08:17

import django.core.validators
from django.db import migrations, models
import rcmsApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rcmsApp', '0035_productcategory_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='products',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Only JPEG/JPG files are allowed.'), rcmsApp.models.validate_image_size]),
        ),
    ]
